// 听力数据 - 20道听力练习
var listeningData = [
    {id: 1, title: "Campus Life", speaker: "American Female", difficulty: "中等", transcript: "The university library has extended its ___ hours during finals week.", blank: "operating", keysentence: "The university library has extended its operating hours during finals week."},
    {id: 2, title: "Academic Research", speaker: "American Male", difficulty: "中等", transcript: "The professor emphasized the importance of ___ sources in academic writing.", blank: "credible", keysentence: "The professor emphasized the importance of credible sources in academic writing."},
    {id: 3, title: "Environmental Science", speaker: "American Female", difficulty: "较难", transcript: "Climate change has led to a significant ___ in global biodiversity.", blank: "decline", keysentence: "Climate change has led to a significant decline in global biodiversity."},
    {id: 4, title: "Technology Innovation", speaker: "American Male", difficulty: "中等", transcript: "Artificial intelligence is ___ transforming various industries.", blank: "rapidly", keysentence: "Artificial intelligence is rapidly transforming various industries."},
    {id: 5, title: "Economic Analysis", speaker: "American Female", difficulty: "较难", transcript: "The central bank decided to raise interest rates to combat ___.", blank: "inflation", keysentence: "The central bank decided to raise interest rates to combat inflation."},
    {id: 6, title: "Medical Research", speaker: "American Male", difficulty: "较难", transcript: "The clinical trial showed ___ results for the new treatment.", blank: "promising", keysentence: "The clinical trial showed promising results for the new treatment."},
    {id: 7, title: "Social Psychology", speaker: "American Female", difficulty: "中等", transcript: "Group dynamics can significantly ___ individual decision-making.", blank: "influence", keysentence: "Group dynamics can significantly influence individual decision-making."},
    {id: 8, title: "Art History", speaker: "American Male", difficulty: "中等", transcript: "The Renaissance period marked a ___ in European artistic expression.", blank: "revolution", keysentence: "The Renaissance period marked a revolution in European artistic expression."},
    {id: 9, title: "Linguistics", speaker: "American Female", difficulty: "较难", transcript: "Language acquisition in children follows a ___ developmental pattern.", blank: "predictable", keysentence: "Language acquisition in children follows a predictable developmental pattern."},
    {id: 10, title: "Astronomy", speaker: "American Male", difficulty: "中等", transcript: "Scientists have discovered a potentially ___ exoplanet in a nearby star system.", blank: "habitable", keysentence: "Scientists have discovered a potentially habitable exoplanet in a nearby star system."},
    {id: 11, title: "Philosophy", speaker: "American Female", difficulty: "较难", transcript: "The concept of free will remains a ___ topic in philosophical debates.", blank: "controversial", keysentence: "The concept of free will remains a controversial topic in philosophical debates."},
    {id: 12, title: "Neuroscience", speaker: "American Male", difficulty: "较难", transcript: "The brain's ___ allows it to adapt and reorganize throughout life.", blank: "plasticity", keysentence: "The brain's plasticity allows it to adapt and reorganize throughout life."},
    {id: 13, title: "Political Science", speaker: "American Female", difficulty: "中等", transcript: "Democratic institutions require active citizen ___ to function effectively.", blank: "participation", keysentence: "Democratic institutions require active citizen participation to function effectively."},
    {id: 14, title: "Anthropology", speaker: "American Male", difficulty: "中等", transcript: "Cultural traditions are ___ from one generation to the next.", blank: "transmitted", keysentence: "Cultural traditions are transmitted from one generation to the next."},
    {id: 15, title: "Chemistry", speaker: "American Female", difficulty: "较难", transcript: "The chemical reaction produces a ___ compound with unique properties.", blank: "stable", keysentence: "The chemical reaction produces a stable compound with unique properties."},
    {id: 16, title: "Sociology", speaker: "American Male", difficulty: "中等", transcript: "Social media has ___ changed how people communicate globally.", blank: "fundamentally", keysentence: "Social media has fundamentally changed how people communicate globally."},
    {id: 17, title: "Biology", speaker: "American Female", difficulty: "中等", transcript: "Genetic mutations can lead to ___ in species over time.", blank: "evolution", keysentence: "Genetic mutations can lead to evolution in species over time."},
    {id: 18, title: "Architecture", speaker: "American Male", difficulty: "中等", transcript: "Sustainable building design prioritizes energy ___ and environmental impact.", blank: "efficiency", keysentence: "Sustainable building design prioritizes energy efficiency and environmental impact."},
    {id: 19, title: "Education Theory", speaker: "American Female", difficulty: "较难", transcript: "Constructivist learning theory emphasizes students' active ___ of knowledge.", blank: "construction", keysentence: "Constructivist learning theory emphasizes students' active construction of knowledge."},
    {id: 20, title: "Data Science", speaker: "American Male", difficulty: "较难", transcript: "Machine learning algorithms can identify ___ patterns in large datasets.", blank: "complex", keysentence: "Machine learning algorithms can identify complex patterns in large datasets."}
];

// 口语跟读句子 - 100句
var speakingSentences = [
    // 学术表达 (20句)
    "The research findings suggest a strong correlation between the variables.",
    "This study aims to investigate the underlying mechanisms of cognitive development.",
    "The methodology employed in this experiment ensures reliable results.",
    "According to the latest scientific evidence, climate change is accelerating.",
    "The theoretical framework provides a comprehensive understanding of the phenomenon.",
    "Statistical analysis reveals significant differences between the two groups.",
    "The implications of this discovery extend beyond the scientific community.",
    "Further research is needed to validate these preliminary conclusions.",
    "The hypothesis was supported by empirical data collected over three years.",
    "This paper contributes to the growing body of literature on artificial intelligence.",
    "The experimental design controlled for potential confounding variables.",
    "Our findings are consistent with previous studies in this field.",
    "The data demonstrates a clear trend toward increased globalization.",
    "This phenomenon can be attributed to multiple interconnected factors.",
    "The study limitations should be considered when interpreting results.",
    "Qualitative analysis complemented the quantitative findings effectively.",
    "The peer review process ensures academic integrity and quality.",
    "Cross-cultural comparisons reveal interesting patterns of behavior.",
    "The theoretical model accurately predicts observed outcomes.",
    "Future studies should explore alternative explanations for these results.",
    
    // 日常会话 (20句)
    "Could you please repeat that? I didn't quite catch what you said.",
    "I appreciate your help with this matter. Thank you so much.",
    "Would you mind if I asked you a few questions about your experience?",
    "I'm sorry for the inconvenience. Let me see what I can do.",
    "That's a really good point. I hadn't thought of it that way.",
    "I completely understand your concern. Let's work through this together.",
    "Could we schedule a meeting to discuss this further?",
    "I think there might be some misunderstanding. Let me clarify.",
    "What are your thoughts on the new proposal?",
    "I'd be happy to help you with that assignment.",
    "Let me know if you need any additional information.",
    "I'm looking forward to our collaboration on this project.",
    "Could you elaborate on that point a little more?",
    "That makes perfect sense. Thank you for explaining.",
    "I agree with your assessment of the situation.",
    "Would it be possible to get an extension on the deadline?",
    "I'm afraid I won't be able to make it to the meeting tomorrow.",
    "Please feel free to reach out if you have any questions.",
    "I really enjoyed our conversation today.",
    "Let's touch base again next week to check on progress.",
    
    // 商务英语 (20句)
    "We need to streamline our operations to improve efficiency.",
    "The quarterly report shows a significant increase in revenue.",
    "Our competitive advantage lies in our innovative approach.",
    "The market analysis indicates strong growth potential.",
    "We should leverage our existing resources more effectively.",
    "The stakeholders have expressed concerns about the timeline.",
    "Let's brainstorm some creative solutions to this challenge.",
    "The ROI on this investment exceeds our initial projections.",
    "We need to align our strategies with the company's long-term goals.",
    "Customer satisfaction remains our top priority.",
    "The merger will create synergies across multiple departments.",
    "We're committed to delivering high-quality products and services.",
    "The budget constraints require us to prioritize essential projects.",
    "Our team has demonstrated exceptional performance this quarter.",
    "The partnership offers mutual benefits for both organizations.",
    "We should diversify our portfolio to minimize risk.",
    "The action items from today's meeting need immediate attention.",
    "Let's schedule a follow-up call to finalize the details.",
    "The implementation timeline is ambitious but achievable.",
    "We appreciate your continued support and partnership.",
    
    // GRE/TOEFL高频 (20句)
    "The author's argument relies heavily on unsubstantiated claims.",
    "The passage implies that technological advancement has drawbacks.",
    "In contrast to popular belief, the evidence suggests otherwise.",
    "The phenomenon described in the lecture contradicts the reading.",
    "Several factors contribute to the complexity of this issue.",
    "The speaker draws a distinction between theory and practice.",
    "This interpretation challenges conventional wisdom on the subject.",
    "The analogy effectively illustrates the main concept.",
    "The author acknowledges the limitations of the proposed solution.",
    "The evidence presented is insufficient to support the conclusion.",
    "The two viewpoints are fundamentally incompatible.",
    "The historical context is essential for understanding this development.",
    "The reading and lecture present conflicting perspectives on the issue.",
    "The underlying assumption of the argument is questionable.",
    "The phenomenon can be explained by multiple competing theories.",
    "The statistical data corroborates the researcher's hypothesis.",
    "The author employs rhetorical strategies to persuade the reader.",
    "The implications of this policy extend to various sectors.",
    "The correlation does not necessarily imply causation.",
    "The study's methodology has been criticized by other researchers.",
    
    // 科技主题 (20句)
    "Artificial intelligence is revolutionizing multiple industries.",
    "The algorithm processes millions of data points per second.",
    "Cloud computing has transformed how businesses store information.",
    "Cybersecurity threats continue to evolve and become more sophisticated.",
    "The user interface should be intuitive and accessible.",
    "Machine learning models require extensive training data.",
    "The software update includes several bug fixes and improvements.",
    "Blockchain technology ensures transparency and security in transactions.",
    "Virtual reality creates immersive experiences for users.",
    "The Internet of Things connects everyday devices to the network.",
    "Data privacy regulations affect how companies handle user information.",
    "The startup secured funding to scale their innovative platform.",
    "Autonomous vehicles rely on sensors and artificial intelligence.",
    "The digital transformation has accelerated due to recent events.",
    "Renewable energy technology continues to improve in efficiency.",
    "The quantum computer can solve complex problems exponentially faster.",
    "Social media algorithms influence what content users see.",
    "The tech industry faces increasing scrutiny over ethical concerns.",
    "Biotechnology advances are enabling personalized medicine.",
    "The application uses encryption to protect sensitive data."
];
