// 名人名言库 - 100条精选哲理名言
var QUOTES = [
    { text: "知识就是力量。", author: "培根" },
    { text: "学而不思则罔，思而不学则殆。", author: "孔子" },
    { text: "天才是百分之一的灵感加百分之九十九的汗水。", author: "爱迪生" },
    { text: "生活不是等待风暴过去，而是学会在雨中起舞。", author: "佚名" },
    { text: "己所不欲，勿施于人。", author: "孔子" },
    { text: "时间就是生命，时间就是速度，时间就是力量。", author: "郭沫若" },
    { text: "书山有路勤为径，学海无涯苦作舟。", author: "韩愈" },
    { text: "失败是成功之母。", author: "谚语" },
    { text: "路漫漫其修远兮，吾将上下而求索。", author: "屈原" },
    { text: "三人行，必有我师焉。", author: "孔子" },
    { text: "世上无难事，只要肯登攀。", author: "毛泽东" },
    { text: "千里之行，始于足下。", author: "老子" },
    { text: "不积跬步，无以至千里。", author: "荀子" },
    { text: "业精于勤，荒于嬉。", author: "韩愈" },
    { text: "读书破万卷，下笔如有神。", author: "杜甫" },
    { text: "温故而知新，可以为师矣。", author: "孔子" },
    { text: "吾生也有涯，而知也无涯。", author: "庄子" },
    { text: "宝剑锋从磨砺出，梅花香自苦寒来。", author: "佚名" },
    { text: "少壮不努力，老大徒伤悲。", author: "汉乐府" },
    { text: "黑发不知勤学早，白首方悔读书迟。", author: "颜真卿" },
    { text: "人生在勤，不索何获。", author: "张衡" },
    { text: "天行健，君子以自强不息。", author: "《周易》" },
    { text: "志当存高远。", author: "诸葛亮" },
    { text: "穷且益坚，不坠青云之志。", author: "王勃" },
    { text: "老骥伏枥，志在千里。", author: "曹操" },
    { text: "海纳百川，有容乃大。", author: "林则徐" },
    { text: "会当凌绝顶，一览众山小。", author: "杜甫" },
    { text: "长风破浪会有时，直挂云帆济沧海。", author: "李白" },
    { text: "不经一番寒彻骨，怎得梅花扑鼻香。", author: "黄檗禅师" },
    { text: "纸上得来终觉浅，绝知此事要躬行。", author: "陆游" },
    { text: "读万卷书，行万里路。", author: "顾炎武" },
    { text: "问渠那得清如许，为有源头活水来。", author: "朱熹" },
    { text: "锲而不舍，金石可镂。", author: "荀子" },
    { text: "博观而约取，厚积而薄发。", author: "苏轼" },
    { text: "不畏浮云遮望眼，只缘身在最高层。", author: "王安石" },
    { text: "欲穷千里目，更上一层楼。", author: "王之涣" },
    { text: "落红不是无情物，化作春泥更护花。", author: "龚自珍" },
    { text: "横眉冷对千夫指，俯首甘为孺子牛。", author: "鲁迅" },
    { text: "人生自古谁无死，留取丹心照汗青。", author: "文天祥" },
    { text: "粉身碎骨浑不怕，要留清白在人间。", author: "于谦" },
    { text: "先天下之忧而忧，后天下之乐而乐。", author: "范仲淹" },
    { text: "人无远虑，必有近忧。", author: "孔子" },
    { text: "知之为知之，不知为不知，是知也。", author: "孔子" },
    { text: "敏而好学，不耻下问。", author: "孔子" },
    { text: "学然后知不足。", author: "《礼记》" },
    { text: "玉不琢，不成器；人不学，不知道。", author: "《礼记》" },
    { text: "逝者如斯夫，不舍昼夜。", author: "孔子" },
    { text: "工欲善其事，必先利其器。", author: "孔子" },
    { text: "知者不惑，仁者不忧，勇者不惧。", author: "孔子" },
    { text: "见贤思齐焉，见不贤而内自省也。", author: "孔子" },
    { text: "The only way to do great work is to love what you do.", author: "乔布斯" },
    { text: "Stay hungry, stay foolish.", author: "乔布斯" },
    { text: "Be the change you wish to see in the world.", author: "甘地" },
    { text: "In the middle of difficulty lies opportunity.", author: "爱因斯坦" },
    { text: "Life is what happens when you're busy making plans.", author: "约翰·列侬" },
    { text: "The future belongs to those who believe in their dreams.", author: "罗斯福" },
    { text: "Success is not final, failure is not fatal.", author: "丘吉尔" },
    { text: "The only thing we have to fear is fear itself.", author: "罗斯福" },
    { text: "I think, therefore I am.", author: "笛卡尔" },
    { text: "To be or not to be, that is the question.", author: "莎士比亚" },
    { text: "知足者常乐。", author: "老子" },
    { text: "静以修身，俭以养德。", author: "诸葛亮" },
    { text: "勿以善小而不为，勿以恶小而为之。", author: "刘备" },
    { text: "天生我材必有用。", author: "李白" },
    { text: "仰天大笑出门去，我辈岂是蓬蒿人。", author: "李白" },
    { text: "山重水复疑无路，柳暗花明又一村。", author: "陆游" },
    { text: "沉舟侧畔千帆过，病树前头万木春。", author: "刘禹锡" },
    { text: "海内存知己，天涯若比邻。", author: "王勃" },
    { text: "莫愁前路无知己，天下谁人不识君。", author: "高适" },
    { text: "人生得意须尽欢，莫使金樽空对月。", author: "李白" },
    { text: "采得百花成蜜后，为谁辛苦为谁甜。", author: "罗隐" },
    { text: "春蚕到死丝方尽，蜡炬成灰泪始干。", author: "李商隐" },
    { text: "随风潜入夜，润物细无声。", author: "杜甫" },
    { text: "不识庐山真面目，只缘身在此山中。", author: "苏轼" },
    { text: "人有悲欢离合，月有阴晴圆缺。", author: "苏轼" },
    { text: "但愿人长久，千里共婵娟。", author: "苏轼" },
    { text: "大江东去，浪淘尽，千古风流人物。", author: "苏轼" },
    { text: "人间正道是沧桑。", author: "毛泽东" },
    { text: "雄关漫道真如铁，而今迈步从头越。", author: "毛泽东" },
    { text: "星星之火，可以燎原。", author: "毛泽东" },
    { text: "实践是检验真理的唯一标准。", author: "邓小平" },
    { text: "科学技术是第一生产力。", author: "邓小平" },
    { text: "吃一堑，长一智。", author: "谚语" },
    { text: "绳锯木断，水滴石穿。", author: "罗大经" },
    { text: "精诚所至，金石为开。", author: "王充" },
    { text: "不飞则已，一飞冲天。", author: "司马迁" },
    { text: "燕雀安知鸿鹄之志哉。", author: "司马迁" },
    { text: "桃李不言，下自成蹊。", author: "司马迁" },
    { text: "风声雨声读书声，声声入耳。", author: "顾宪成" },
    { text: "家事国事天下事，事事关心。", author: "顾宪成" },
    { text: "位卑未敢忘忧国。", author: "陆游" },
    { text: "苟利国家生死以，岂因祸福避趋之。", author: "林则徐" },
    { text: "青山遮不住，毕竟东流去。", author: "辛弃疾" },
    { text: "众里寻他千百度，蓦然回首那人却在灯火阑珊处。", author: "辛弃疾" },
    { text: "世事洞明皆学问，人情练达即文章。", author: "曹雪芹" },
    { text: "机关算尽太聪明，反误了卿卿性命。", author: "曹雪芹" },
    { text: "满招损，谦受益。", author: "《尚书》" },
    { text: "他山之石，可以攻玉。", author: "《诗经》" },
    { text: "前事不忘，后事之师。", author: "《战国策》" },
    
    // ===== 新增300条名人名言 =====
    // 中国古代哲理
    { text: "上善若水，水善利万物而不争。", author: "老子" },
    { text: "大道至简。", author: "老子" },
    { text: "合抱之木，生于毫末。", author: "老子" },
    { text: "祸兮福之所倚，福兮祸之所伏。", author: "老子" },
    { text: "知人者智，自知者明。", author: "老子" },
    { text: "道生一，一生二，二生三，三生万物。", author: "老子" },
    { text: "治大国如烹小鲜。", author: "老子" },
    { text: "天地不仁，以万物为刍狗。", author: "老子" },
    { text: "大音希声，大象无形。", author: "老子" },
    { text: "道可道，非常道。", author: "老子" },
    { text: "相濡以沫，不如相忘于江湖。", author: "庄子" },
    { text: "井蛙不可以语于海者，拘于虚也。", author: "庄子" },
    { text: "朝菌不知晦朔，蟪蛄不知春秋。", author: "庄子" },
    { text: "庖丁解牛，游刃有余。", author: "庄子" },
    { text: "物物而不物于物。", author: "庄子" },
    { text: "子非鱼，安知鱼之乐？", author: "庄子" },
    { text: "天地与我并生，万物与我为一。", author: "庄子" },
    { text: "至人无己，神人无功，圣人无名。", author: "庄子" },
    { text: "君子坦荡荡，小人长戚戚。", author: "孔子" },
    { text: "学而时习之，不亦说乎。", author: "孔子" },
    { text: "有朋自远方来，不亦乐乎。", author: "孔子" },
    { text: "人不知而不愠，不亦君子乎。", author: "孔子" },
    { text: "岁寒，然后知松柏之后凋也。", author: "孔子" },
    { text: "君子和而不同，小人同而不和。", author: "孔子" },
    { text: "君子成人之美，不成人之恶。", author: "孔子" },
    { text: "名不正则言不顺，言不顺则事不成。", author: "孔子" },
    { text: "知之者不如好之者，好之者不如乐之者。", author: "孔子" },
    { text: "默而识之，学而不厌，诲人不倦。", author: "孔子" },
    { text: "不愤不启，不悱不发。", author: "孔子" },
    { text: "发愤忘食，乐以忘忧，不知老之将至。", author: "孔子" },
    { text: "志士仁人，无求生以害仁，有杀身以成仁。", author: "孔子" },
    { text: "天下兴亡，匹夫有责。", author: "顾炎武" },
    { text: "民为贵，社稷次之，君为轻。", author: "孟子" },
    { text: "富贵不能淫，贫贱不能移，威武不能屈。", author: "孟子" },
    { text: "生于忧患，死于安乐。", author: "孟子" },
    { text: "天时不如地利，地利不如人和。", author: "孟子" },
    { text: "得道者多助，失道者寡助。", author: "孟子" },
    { text: "老吾老以及人之老，幼吾幼以及人之幼。", author: "孟子" },
    { text: "尽信书则不如无书。", author: "孟子" },
    { text: "穷则独善其身，达则兼善天下。", author: "孟子" },
    { text: "仁者爱人，有礼者敬人。", author: "孟子" },
    { text: "人皆可以为尧舜。", author: "孟子" },
    { text: "青，取之于蓝，而青于蓝。", author: "荀子" },
    { text: "骐骥一跃，不能十步；驽马十驾，功在不舍。", author: "荀子" },
    { text: "蓬生麻中，不扶而直。", author: "荀子" },
    { text: "水能载舟，亦能覆舟。", author: "荀子" },
    { text: "见善如不及，见不善如探汤。", author: "荀子" },
    { text: "君子博学而日参省乎己。", author: "荀子" },
    { text: "兼听则明，偏信则暗。", author: "魏征" },
    { text: "以铜为镜，可以正衣冠。", author: "魏征" },
    { text: "水至清则无鱼，人至察则无徒。", author: "东方朔" },
    
    // 中国古代诗词名句
    { text: "大漠孤烟直，长河落日圆。", author: "王维" },
    { text: "行到水穷处，坐看云起时。", author: "王维" },
    { text: "明月松间照，清泉石上流。", author: "王维" },
    { text: "劝君更尽一杯酒，西出阳关无故人。", author: "王维" },
    { text: "独在异乡为异客，每逢佳节倍思亲。", author: "王维" },
    { text: "红豆生南国，春来发几枝。", author: "王维" },
    { text: "空山新雨后，天气晚来秋。", author: "王维" },
    { text: "抽刀断水水更流，举杯消愁愁更愁。", author: "李白" },
    { text: "两岸猿声啼不住，轻舟已过万重山。", author: "李白" },
    { text: "举头望明月，低头思故乡。", author: "李白" },
    { text: "飞流直下三千尺，疑是银河落九天。", author: "李白" },
    { text: "桃花潭水深千尺，不及汪伦送我情。", author: "李白" },
    { text: "黄河之水天上来，奔流到海不复回。", author: "李白" },
    { text: "安能摧眉折腰事权贵，使我不得开心颜。", author: "李白" },
    { text: "两情若是久长时，又岂在朝朝暮暮。", author: "秦观" },
    { text: "衣带渐宽终不悔，为伊消得人憔悴。", author: "柳永" },
    { text: "今宵酒醒何处，杨柳岸晓风残月。", author: "柳永" },
    { text: "执手相看泪眼，竟无语凝噎。", author: "柳永" },
    { text: "无可奈何花落去，似曾相识燕归来。", author: "晏殊" },
    { text: "昨夜西风凋碧树，独上高楼，望尽天涯路。", author: "晏殊" },
    { text: "春风又绿江南岸，明月何时照我还。", author: "王安石" },
    { text: "看似寻常最奇崛，成如容易却艰辛。", author: "王安石" },
    { text: "千门万户曈曈日，总把新桃换旧符。", author: "王安石" },
    { text: "醉翁之意不在酒，在乎山水之间也。", author: "欧阳修" },
    { text: "残雪压枝犹有橘，冻雷惊笋欲抽芽。", author: "欧阳修" },
    { text: "等闲识得东风面，万紫千红总是春。", author: "朱熹" },
    { text: "少年易学老难成，一寸光阴不可轻。", author: "朱熹" },
    { text: "半亩方塘一鉴开，天光云影共徘徊。", author: "朱熹" },
    { text: "小楼一夜听春雨，深巷明朝卖杏花。", author: "陆游" },
    { text: "王师北定中原日，家祭无忘告乃翁。", author: "陆游" },
    { text: "夜阑卧听风吹雨，铁马冰河入梦来。", author: "陆游" },
    { text: "千淘万漉虽辛苦，吹尽狂沙始到金。", author: "刘禹锡" },
    { text: "旧时王谢堂前燕，飞入寻常百姓家。", author: "刘禹锡" },
    { text: "自古逢秋悲寂寥，我言秋日胜春朝。", author: "刘禹锡" },
    { text: "问君能有几多愁，恰似一江春水向东流。", author: "李煜" },
    { text: "春花秋月何时了，往事知多少。", author: "李煜" },
    { text: "雕栏玉砌应犹在，只是朱颜改。", author: "李煜" },
    { text: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。", author: "李清照" },
    { text: "此情无计可消除，才下眉头，却上心头。", author: "李清照" },
    { text: "生当作人杰，死亦为鬼雄。", author: "李清照" },
    { text: "莫道不消魂，帘卷西风，人比黄花瘦。", author: "李清照" },
    { text: "知否知否，应是绿肥红瘦。", author: "李清照" },
    { text: "了却君王天下事，赢得生前身后名。", author: "辛弃疾" },
    { text: "醉里挑灯看剑，梦回吹角连营。", author: "辛弃疾" },
    { text: "少年不识愁滋味，爱上层楼。", author: "辛弃疾" },
    { text: "把吴钩看了，栏杆拍遍，无人会，登临意。", author: "辛弃疾" },
    { text: "凭谁问，廉颇老矣，尚能饭否。", author: "辛弃疾" },
    { text: "明日复明日，明日何其多。", author: "钱福" },
    { text: "一寸光阴一寸金，寸金难买寸光阴。", author: "《增广贤文》" },
    { text: "书中自有黄金屋，书中自有颜如玉。", author: "赵恒" },
    { text: "读书百遍，其义自见。", author: "裴松之" },
    { text: "书到用时方恨少，事非经过不知难。", author: "陆游" },
    
    // 近现代名人名言
    { text: "寄意寒星荃不察，我以我血荐轩辕。", author: "鲁迅" },
    { text: "其实地上本没有路，走的人多了便成了路。", author: "鲁迅" },
    { text: "不在沉默中爆发，就在沉默中灭亡。", author: "鲁迅" },
    { text: "哀其不幸，怒其不争。", author: "鲁迅" },
    { text: "真的猛士，敢于直面惨淡的人生。", author: "鲁迅" },
    { text: "时间就像海绵里的水，只要愿挤总还是有的。", author: "鲁迅" },
    { text: "希望本是无所谓有，无所谓无的。", author: "鲁迅" },
    { text: "走自己的路，让别人说去吧。", author: "但丁" },
    { text: "数风流人物，还看今朝。", author: "毛泽东" },
    { text: "一万年太久，只争朝夕。", author: "毛泽东" },
    { text: "好好学习，天天向上。", author: "毛泽东" },
    { text: "为人民服务。", author: "毛泽东" },
    { text: "自己动手，丰衣足食。", author: "毛泽东" },
    { text: "虚心使人进步，骄傲使人落后。", author: "毛泽东" },
    { text: "世界是你们的，也是我们的，但归根结底是你们的。", author: "毛泽东" },
    { text: "天若有情天亦老，人间正道是沧桑。", author: "毛泽东" },
    { text: "发展才是硬道理。", author: "邓小平" },
    { text: "解放思想，实事求是。", author: "邓小平" },
    { text: "摸着石头过河。", author: "邓小平" },
    { text: "不管黑猫白猫，抓到老鼠就是好猫。", author: "邓小平" },
    { text: "允许一部分人先富起来。", author: "邓小平" },
    { text: "为中华之崛起而读书。", author: "周恩来" },
    { text: "自信人生二百年，会当水击三千里。", author: "毛泽东" },
    { text: "人固有一死，或重于泰山，或轻于鸿毛。", author: "司马迁" },
    { text: "士为知己者死，女为悦己者容。", author: "司马迁" },
    
    // 西方哲学与思想
    { text: "我思故我在。", author: "笛卡尔" },
    { text: "人是万物的尺度。", author: "普罗泰戈拉" },
    { text: "认识你自己。", author: "苏格拉底" },
    { text: "我唯一知道的就是我一无所知。", author: "苏格拉底" },
    { text: "未经审视的人生不值得过。", author: "苏格拉底" },
    { text: "吾爱吾师，吾更爱真理。", author: "亚里士多德" },
    { text: "人天生是政治的动物。", author: "亚里士多德" },
    { text: "美德是一种行为习惯。", author: "亚里士多德" },
    { text: "人人生而平等。", author: "卢梭" },
    { text: "人是生而自由的，却无往不在枷锁之中。", author: "卢梭" },
    { text: "存在即合理。", author: "黑格尔" },
    { text: "世界历史就是自由意识的进步。", author: "黑格尔" },
    { text: "人只不过是一根芦苇，但他是一根能思想的芦苇。", author: "帕斯卡尔" },
    { text: "给我一个支点，我就能撬动地球。", author: "阿基米德" },
    { text: "上帝死了。", author: "尼采" },
    { text: "那些杀不死我的，必将使我更强大。", author: "尼采" },
    { text: "与怪物战斗的人，小心自己不要成为怪物。", author: "尼采" },
    { text: "当你凝视深渊时，深渊也在凝视你。", author: "尼采" },
    { text: "他人即地狱。", author: "萨特" },
    { text: "存在先于本质。", author: "萨特" },
    { text: "人被判定为自由的。", author: "萨特" },
    { text: "世界上只有一种英雄主义，就是认清生活真相后依然热爱生活。", author: "罗曼·罗兰" },
    { text: "真正的光明不是没有黑暗的时刻，只是永远不被黑暗所掩蔽。", author: "罗曼·罗兰" },
    
    // 科学家名言
    { text: "想象力比知识更重要。", author: "爱因斯坦" },
    { text: "逻辑会把你从A带到B，想象力能带你去任何地方。", author: "爱因斯坦" },
    { text: "我没有特别的天赋，我只是极度好奇。", author: "爱因斯坦" },
    { text: "宇宙最不可理解的事情是它竟然是可以理解的。", author: "爱因斯坦" },
    { text: "问题不能在产生它的同一思维层面上被解决。", author: "爱因斯坦" },
    { text: "一个人的价值不在于他获得了什么，而在于他奉献了什么。", author: "爱因斯坦" },
    { text: "如果我比别人看得更远，那是因为我站在巨人的肩膀上。", author: "牛顿" },
    { text: "我可以计算天体运行的轨道，却无法计算人性的疯狂。", author: "牛顿" },
    { text: "在科学的入口处，正像在地狱的入口处一样。", author: "马克思" },
    { text: "全世界无产者，联合起来！", author: "马克思" },
    { text: "哲学家们只是用不同的方式解释世界，问题在于改变世界。", author: "马克思" },
    { text: "知识是人类进步的阶梯。", author: "高尔基" },
    { text: "书籍是人类进步的阶梯。", author: "高尔基" },
    { text: "我扑在书上，就像饥饿的人扑在面包上。", author: "高尔基" },
    { text: "天才出于勤奋。", author: "高尔基" },
    { text: "发明是百分之一的灵感加百分之九十九的汗水。", author: "爱迪生" },
    { text: "许多人生活中的失败，是因为他们没有意识到自己离成功有多近。", author: "爱迪生" },
    { text: "我们最大的弱点在于放弃，成功的必然之路就是不断尝试。", author: "爱迪生" },
    { text: "机会总是留给有准备的人。", author: "巴斯德" },
    { text: "在观察的领域中，机遇只偏爱那种有准备的头脑。", author: "巴斯德" },
    { text: "我的整个生命和全部精力，都已经献给了世界上最壮丽的事业——为人类的解放而斗争。", author: "奥斯特洛夫斯基" },
    { text: "生命中真正重要的不是你遭遇了什么，而是你记住了什么。", author: "马尔克斯" },
    
    // 文学家名言
    { text: "冬天来了，春天还会远吗？", author: "雪莱" },
    { text: "生存还是毁灭，这是一个值得思考的问题。", author: "莎士比亚" },
    { text: "简洁是智慧的灵魂，冗长是浅薄的藻饰。", author: "莎士比亚" },
    { text: "玫瑰即使换一个名字，依然芬芳如故。", author: "莎士比亚" },
    { text: "懦夫在未死之前，就已经死过好多次。", author: "莎士比亚" },
    { text: "黑夜无论怎样悠长，白昼总会到来。", author: "莎士比亚" },
    { text: "世界是一个舞台，所有男女都是演员。", author: "莎士比亚" },
    { text: "明智的人绝不坐下来为失败而哀号，他们一定乐观地寻找办法来加以挽救。", author: "莎士比亚" },
    { text: "幸福的家庭都是相似的，不幸的家庭各有各的不幸。", author: "托尔斯泰" },
    { text: "人并非为吃而活着，而是为活着而吃。", author: "托尔斯泰" },
    { text: "一个人必须认识真理，并且要把它实践出来。", author: "托尔斯泰" },
    { text: "理想的书籍是智慧的钥匙。", author: "托尔斯泰" },
    { text: "人生不是一种享乐，而是一桩十分沉重的工作。", author: "托尔斯泰" },
    { text: "一个人只有在独处时才能成为自己。", author: "叔本华" },
    { text: "人生就像钟摆，在痛苦和无聊之间摆动。", author: "叔本华" },
    { text: "人性能够达到的最高境界是没有人能达到的。", author: "叔本华" },
    { text: "要么庸俗，要么孤独。", author: "叔本华" },
    { text: "生活需要仪式感。", author: "佚名" },
    { text: "心有多大，舞台就有多大。", author: "佚名" },
    { text: "态度决定高度，习惯决定命运。", author: "佚名" },
    { text: "今天很残酷，明天更残酷，后天很美好。", author: "马云" },
    { text: "梦想还是要有的，万一实现了呢。", author: "马云" },
    { text: "如果你不喜欢现在的生活，要么换一种活法，要么闭嘴。", author: "马云" },
    { text: "永远不要跟别人比幸运，我从来没想过我比别人幸运。", author: "马云" },
    { text: "一个人的成功不取决于他的智慧，而是取决于他的毅力。", author: "巴菲特" },
    { text: "风险来自你不知道自己在做什么。", author: "巴菲特" },
    { text: "别人贪婪时我恐惧，别人恐惧时我贪婪。", author: "巴菲特" },
    { text: "时间是优秀企业的朋友，是平庸企业的敌人。", author: "巴菲特" },
    
    // 励志名言
    { text: "不要问国家能为你做什么，问你能为国家做什么。", author: "肯尼迪" },
    { text: "如果你想走得快，就一个人走；如果你想走得远，就一群人走。", author: "非洲谚语" },
    { text: "成功是一段旅程，而非目的地。", author: "佚名" },
    { text: "每一个不曾起舞的日子，都是对生命的辜负。", author: "尼采" },
    { text: "你若盛开，蝴蝶自来；你若精彩，天自安排。", author: "佚名" },
    { text: "越努力，越幸运。", author: "佚名" },
    { text: "做最好的自己，才能碰见最好的别人。", author: "佚名" },
    { text: "与其临渊羡鱼，不如退而结网。", author: "《汉书》" },
    { text: "人生最大的敌人是自己，最大的失败是自大。", author: "佚名" },
    { text: "把每一天当作最后一天来过，你就会活得更有意义。", author: "佚名" },
    { text: "努力不一定成功，但不努力一定不成功。", author: "佚名" },
    { text: "方向比速度更重要。", author: "佚名" },
    { text: "成功的秘诀在于永不言弃。", author: "丘吉尔" },
    { text: "勇气就是优雅地面对压力。", author: "海明威" },
    { text: "一个人可以被毁灭，但不能被打败。", author: "海明威" },
    { text: "这个世界那么美好，值得人们为它奋斗。", author: "海明威" },
    { text: "所有坚韧不拔的努力迟早会取得报酬的。", author: "安格尔" },
    { text: "伟大的事业不是靠力气、速度和身体的敏捷完成的，而是靠性格、意志和知识的力量完成的。", author: "塞缪尔·约翰逊" },
    { text: "成功是一种习惯，失败也是一种习惯。", author: "佚名" },
    { text: "人之所以能，是相信能。", author: "佚名" },
    { text: "没有人可以回到过去重新开始，但每个人都可以从今天开始创造全新的未来。", author: "佚名" },
    { text: "你不能改变风的方向，但你可以调整帆的角度。", author: "佚名" },
    { text: "有志者事竟成。", author: "《后汉书》" },
    { text: "有志者，事竟成，破釜沉舟，百二秦关终属楚。", author: "蒲松龄" },
    { text: "苦心人，天不负，卧薪尝胆，三千越甲可吞吴。", author: "蒲松龄" },
    { text: "成功的人找方法，失败的人找借口。", author: "佚名" },
    { text: "细节决定成败。", author: "汪中求" },
    { text: "简单的事情重复做，你就是专家。", author: "佚名" },
    { text: "重复的事情用心做，你就是赢家。", author: "佚名" },
    { text: "不要为过去哭泣，过去已经过去；不要为未来担忧，未来还没有来。", author: "佚名" },
    { text: "活在当下。", author: "佚名" },
    { text: "每天进步一点点，日积月累便是巨大的成功。", author: "佚名" },
    { text: "不是因为有了希望才坚持，而是因为坚持才有了希望。", author: "佚名" },
    { text: "永远不要停止学习，因为生活永远不会停止教导。", author: "佚名" },
    { text: "最好的投资就是投资自己。", author: "富兰克林" },
    { text: "时间就是金钱。", author: "富兰克林" },
    { text: "诚实是最好的策略。", author: "富兰克林" },
    { text: "早睡早起使人健康、富有、聪明。", author: "富兰克林" },
    { text: "一个今天胜过两个明天。", author: "富兰克林" },
    { text: "读书使人充实，思考使人深邃，交谈使人清醒。", author: "富兰克林" },
    { text: "浪费时间是一件最大的奢侈。", author: "富兰克林" },
    
    // 关于学习
    { text: "活到老，学到老。", author: "谚语" },
    { text: "学无止境。", author: "谚语" },
    { text: "三日不读书，便觉面目可憎。", author: "黄庭坚" },
    { text: "腹有诗书气自华。", author: "苏轼" },
    { text: "读书不觉已春深，一寸光阴一寸金。", author: "王贞白" },
    { text: "书犹药也，善读之可以医愚。", author: "刘向" },
    { text: "读书有三到：谓心到、眼到、口到。", author: "朱熹" },
    { text: "学如逆水行舟，不进则退。", author: "《增广贤文》" },
    { text: "温故而知新。", author: "孔子" },
    { text: "博学之，审问之，慎思之，明辨之，笃行之。", author: "《中庸》" },
    { text: "读书须用意，一字值千金。", author: "《增广贤文》" },
    { text: "书山有路勤为径。", author: "韩愈" },
    { text: "非学无以广才，非志无以成学。", author: "诸葛亮" },
    { text: "学而不思则罔。", author: "孔子" },
    { text: "思而不学则殆。", author: "孔子" },
    { text: "好书不厌百回读。", author: "苏轼" },
    { text: "书读百遍其义自见。", author: "谚语" },
    { text: "旧书不厌百回读，熟读深思子自知。", author: "苏轼" },
    { text: "熟读唐诗三百首，不会作诗也会吟。", author: "孙洙" },
    { text: "读书破万卷。", author: "杜甫" },
    { text: "下笔如有神。", author: "杜甫" },
    { text: "人学始知道。", author: "佚名" },
    { text: "不学自知，不问自晓。", author: "佚名" },
    { text: "玉不琢不成器，人不学不知义。", author: "《三字经》" },
    { text: "学然后知不足，教然后知困。", author: "《礼记》" },
    { text: "教学相长也。", author: "《礼记》" },
    { text: "独学而无友，则孤陋而寡闻。", author: "《礼记》" },
    { text: "善学者，师逸而功倍。", author: "《礼记》" },
    { text: "不学礼，无以立。", author: "孔子" },
    { text: "学以致用。", author: "谚语" }
];

// 获取随机名言
function getRandomQuote() {
    var index = Math.floor(Math.random() * QUOTES.length);
    return QUOTES[index];
}

// 更新名言显示
function updateQuoteDisplay() {
    var quoteTextEl = document.getElementById('quoteText');
    var quoteAuthorEl = document.getElementById('quoteAuthor');
    
    if (!quoteTextEl || !quoteAuthorEl) return;
    
    var quote = getRandomQuote();
    quoteTextEl.textContent = '"' + quote.text + '"';
    quoteAuthorEl.textContent = '—— ' + quote.author;
}

// 点击刷新名言
function refreshQuote() {
    var quoteCard = document.querySelector('.quote-card');
    if (quoteCard) {
        quoteCard.style.opacity = '0';
        quoteCard.style.transform = 'translateY(-5px)';
        setTimeout(function() {
            updateQuoteDisplay();
            quoteCard.style.opacity = '1';
            quoteCard.style.transform = 'translateY(0)';
        }, 200);
    } else {
        updateQuoteDisplay();
    }
}

// 导出
window.getRandomQuote = getRandomQuote;
window.updateQuoteDisplay = updateQuoteDisplay;
window.refreshQuote = refreshQuote;
